Repository mul-meong/backend-gateway, pull requests merged in 2024-11, with the labels that each got.

#5 [🔀 Gateway] 요청 route/filter 및 토큰 검증 구현
  .gitignore
  build.gradle
  src/main/java/com/mulmeong/gateway/GatewayApplication.java
  src/main/java/com/mulmeong/gateway/common/config/CorsConfig.java
  src/main/java/com/mulmeong/gateway/common/exception/BaseException.java
  src/main/java/com/mulmeong/gateway/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/gateway/common/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/mulmeong/gateway/common/jwt/properties/JwtProperties.java
  src/main/java/com/mulmeong/gateway/common/jwt/util/JwtProvider.java
  src/main/java/com/mulmeong/gateway/common/response/BaseResponse.java
  src/main/java/com/mulmeong/gateway/common/response/BaseResponseStatus.java
  src/main/resources/application.properties
Labels: ✨ enhancement

#6 [🚀 Gateway] CI/CD 환경 구축
  .github/workflows/cicd.yaml
  Dockerfile
  build.gradle
  src/test/java/com/mulmeong/gateway/GatewayApplicationTests.java
Labels: 👷 chore, 🚀 deploy

#8 [🚑️ Gateway] CI/CD 파이프라인에서 Dockerfile 찾지 못하는 에러 해결
  .github/workflows/cicd.yaml
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#10 [🚑️ gateway] release build 에러 Resolve
  src/test/java/com/mulmeong/gateway/GatewayApplicationTests.java
Labels: 🚑️ hotfix

#12 [🚑️ Gateway] Docker network 연결
  .github/workflows/cicd.yaml
  Dockerfile
Labels: 🐛 bug, 👷 chore, 🚀 deploy, 🚑️ hotfix

#14 [🔀 Gateway] 응답 및 예외 최종 수정
  src/main/java/com/mulmeong/gateway/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/gateway/common/response/BaseResponse.java
  src/main/java/com/mulmeong/gateway/common/response/BaseResponseStatus.java
Labels: ✨ enhancement

#16 [🚀 Gateway] 응답 및 예외 통일, 타입존 에러 수정, .Yml 수정 반영
  Dockerfile
  src/main/java/com/mulmeong/gateway/common/exception/GlobalExceptionHandler.java
  src/main/java/com/mulmeong/gateway/common/response/BaseResponse.java
  src/main/java/com/mulmeong/gateway/common/response/BaseResponseStatus.java
Labels: 🚀 deploy

#18 [🚀 Gateway] Health Check Controller 구현
  src/main/java/com/mulmeong/gateway/common/health/HealthCheckController.java
Labels: ✨ enhancement, 👷 chore, 🚀 deploy

#20 [🔀 Gateway] Config-server 연동
  build.gradle
  src/main/java/com/mulmeong/gateway/GatewayApplication.java
Labels: ✨ enhancement
